const EXHIBITS = [
  // hall 1 – Домеханическая эпоха
  {id:"abacus",
  hall:"hall1",
  icon:"🧮",
  kicker:"Домеханическая эпоха",
  name:"Абак",
  period:"~3000 до н.э.",
  short:"Ручное счетное устройство.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["счет","интерфейс"],
  sources:[],
  video:"3129e49a5a87867e476707b6dfca7c1a",
  quiz:[
    {question:"Что такое абак?", options:["Калькулятор","Счетное устройство","Компьютер"], correct:1},
    {question:"В каком веке появился абак?", options:["I век","III тысячелетие до н.э.","XX век"], correct:1},
    {question:"Как работает абак?", options:["С электричеством","С костяшками","С шестернями"], correct:1},
    {question:"Где использовался абак?", options:["В Древнем Египте","В космосе","В будущем"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Abacus",
  modalImage:"images/hall1/abakus1.JPG"},

  { id:"antikythera", hall:"hall1", icon:"🪐", kicker:"Домеханическая эпоха", name:"Антикитерский механизм", period:"~II–I век до н.э.", short:"Механический аналоговый вычислитель.", desc:"", history:"", work:"", bullets:[], tags:["аналог","астрономия"], sources:[], video:"", quiz:[{question:"Что такое Антикитерский механизм?", options:["Калькулятор","Астрономический инструмент","Телескоп"], correct:1}, {question:"Когда был найден механизм?", options:["1901 год","100 год","2000 год"], correct:0}, {question:"Как работает механизм?", options:["С шестернями","С электричеством","С магнитами"], correct:0}, {question:"Для чего использовался?", options:["Для счета","Для предсказания затмений","Для рисования"], correct:1}], image:"https://via.placeholder.com/400x300?text=Antikythera", modalImage:"https://via.placeholder.com/500x400?text=Antikythera+Detail" },

  { id:"neperBones", hall:"hall1", icon:"🦴", kicker:"Домеханическая эпоха", name:"Палочки Непера", period:"1617", short:"Инструмент для умножения.", desc:"", history:"", work:"", bullets:[], tags:["умножение","палочки"], sources:[], video:"", quiz:[{question:"Кто изобрел палочки Непера?", options:["Паскаль","Непер","Лейбниц"], correct:1}, {question:"Для чего используются палочки?", options:["Для сложения","Для умножения","Для деления"], correct:1}, {question:"Когда изобретены?", options:["1617","1642","1673"], correct:0}, {question:"Как считывается результат?", options:["По диагоналям","По вертикали","По горизонтали"], correct:0}], image:"https://via.placeholder.com/400x300?text=Neper+Bones", modalImage:"https://via.placeholder.com/500x400?text=Neper+Bones+Detail" },

  { id:"slideRule", hall:"hall1", icon:"📏", kicker:"Домеханическая эпоха", name:"Логарифмическая линейка", period:"1620–1970-е", short:"Механический калькулятор.", desc:"", history:"", work:"", bullets:[], tags:["линейка","логарифм"], sources:[], video:"", quiz:[{question:"Что такое логарифмическая линейка?", options:["Линейка","Калькулятор","Компьютер"], correct:1}, {question:"На чем основана работа?", options:["Логарифмах","Синусах","Косинусах"], correct:0}, {question:"Кто придумал?", options:["Непер","Паскаль","Бэббидж"], correct:0}, {question:"Когда использовалась?", options:["До 1970-х","Сейчас","В будущем"], correct:0}], image:"https://via.placeholder.com/400x300?text=Slide+Rule", modalImage:"https://via.placeholder.com/500x400?text=Slide+Rule+Detail" },

  // hall 2 – Механические и электромеханические вычислители
  { id:"pascaline", hall:"hall2", icon:"🧷", kicker:"Механические вычислители", name:"Машина Паскаля", period:"1642", short:"Механический сумматор.", desc:"", history:"", work:"", bullets:[], tags:["механика"], sources:[], video:"", quiz:[{question:"Кто создал машину Паскаля?", options:["Паскаль","Непер","Лейбниц"], correct:0}, {question:"Для чего создана?", options:["Для счета налогов","Для астрономии","Для ткачества"], correct:0}, {question:"Как работает?", options:["С зубчатыми колесами","С лампами","С транзисторами"], correct:0}, {question:"Когда создана?", options:["1642","1673","1804"], correct:0}], image:"https://via.placeholder.com/400x300?text=Pascaline", modalImage:"https://via.placeholder.com/500x400?text=Pascaline+Detail" },

  { id:"leibnizMachine", hall:"hall2", icon:"⚙️", kicker:"Механические вычислители", name:"Машина Лейбница", period:"1673", short:"Улучшенный механический калькулятор.", desc:"", history:"", work:"", bullets:[], tags:["Лейбниц","механика"], sources:[], video:"", quiz:[{question:"Кто разработал машину Лейбница?", options:["Паскаль","Лейбниц","Жаккар"], correct:1}, {question:"Что добавлено к машине Паскаля?", options:["Умножение","Лампы","Транзисторы"], correct:0}, {question:"Как работает умножение?", options:["С барабанами","С шестернями","С кнопками"], correct:0}, {question:"Когда разработана?", options:["1642","1673","1804"], correct:1}], image:"https://via.placeholder.com/400x300?text=Leibniz+Machine", modalImage:"https://via.placeholder.com/500x400?text=Leibniz+Machine+Detail" },

  { id:"jacquardLoom", hall:"hall2", icon:"🧵", kicker:"Электромеханические вычислители", name:"Ткацкий станок Жаккара", period:"1804", short:"Программируемый ткацкий станок.", desc:"", history:"", work:"", bullets:[], tags:["ткачество","перфокарты"], sources:[], video:"", quiz:[{question:"Что такое ткацкий станок Жаккара?", options:["Калькулятор","Программируемый станок","Телескоп"], correct:1}, {question:"Что использовал для управления?", options:["Перфокарты","Кнопки","Экран"], correct:0}, {question:"Кто изобрел?", options:["Жаккар","Бэббидж","Холлерит"], correct:0}, {question:"Для чего использовался?", options:["Для ткани","Для счета","Для астрономии"], correct:0}], image:"https://via.placeholder.com/400x300?text=Jacquard+Loom", modalImage:"https://via.placeholder.com/500x400?text=Jacquard+Loom+Detail" },

  { id:"babbage", hall:"hall2", icon:"🧠", kicker:"Проекты универсальных машин", name:"Аналитическая машина Бэббиджа", period:"1837", short:"Проект программируемого компьютера.", desc:"", history:"", work:"", bullets:[], tags:["архитектура"], sources:[], video:"", quiz:[{question:"Кто спроектировал Аналитическую машину?", options:["Паскаль","Бэббидж","Холлерит"], correct:1}, {question:"Была ли построена машина?", options:["Да","Нет","Частично"], correct:1}, {question:"Из скольких частей состояла?", options:["2","3","4"], correct:1}, {question:"Что использовалось для управления?", options:["Перфокарты","Кнопки","Экран"], correct:0}], image:"https://via.placeholder.com/400x300?text=Babbage+Machine", modalImage:"https://via.placeholder.com/500x400?text=Babbage+Machine+Detail" },

  { id:"hollerithTabulator", hall:"hall2", icon:"📊", kicker:"Электромеханические вычислители", name:"Табулятор Холлерита", period:"1890", short:"Электромеханическая машина для обработки данных.", desc:"", history:"", work:"", bullets:[], tags:["табулятор","IBM"], sources:[], video:"", quiz:[{question:"Для чего использовался табулятор?", options:["Для переписи","Для ткачества","Для астрономии"], correct:0}, {question:"Кто разработал?", options:["Холлерит","Бэббидж","Жаккар"], correct:0}, {question:"Что считывалось?", options:["Перфокарты","Кнопки","Экран"], correct:0}, {question:"Стала основой для?", options:["IBM","Apple","Google"], correct:0}], image:"https://via.placeholder.com/400x300?text=Hollerith+Tabulator", modalImage:"https://via.placeholder.com/500x400?text=Hollerith+Tabulator+Detail" },

  // hall 3 – Поколения ЭВМ
  { id:"vacuum", hall:"hall3", icon:"🔥", kicker:"Поколения ЭВМ", name:"Ламповые компьютеры", period:"1940-е", short:"Электронные лампы.", desc:"", history:"", work:"", bullets:[], tags:["лампы"], sources:[], video:"", quiz:[{question:"Что использовалось в ламповых компьютерах?", options:["Транзисторы","Лампы","Микросхемы"], correct:1}, {question:"Когда появились?", options:["1940-е","1950-е","1960-е"], correct:0}, {question:"Были ли они большими?", options:["Да","Нет","Средними"], correct:0}, {question:"Как кодировали данные?", options:["Двоично","Десятично","Шестнадцатерично"], correct:0}], image:"https://via.placeholder.com/400x300?text=Vacuum+Tubes", modalImage:"https://via.placeholder.com/500x400?text=Vacuum+Tubes+Detail" },

  { id:"transistor", hall:"hall3", icon:"🟢", kicker:"Поколения ЭВМ", name:"Транзисторные компьютеры", period:"1950-е", short:"Переход к полупроводникам.", desc:"", history:"", work:"", bullets:[], tags:["транзисторы"], sources:[], video:"", quiz:[{question:"Что заменили транзисторы?", options:["Лампы","Микросхемы","Процессоры"], correct:0}, {question:"Когда появились?", options:["1940-е","1950-е","1960-е"], correct:1}, {question:"Стали ли они меньше?", options:["Да","Нет","Больше"], correct:0}, {question:"Как работают транзисторы?", options:["Усиливают сигнал","Генерируют свет","Хранят данные"], correct:0}], image:"https://via.placeholder.com/400x300?text=Transistor", modalImage:"https://via.placeholder.com/500x400?text=Transistor+Detail" },

  { id:"integratedCircuit", hall:"hall3", icon:"🔁", kicker:"Поколения ЭВМ", name:"Компьютеры на интегральных схемах", period:"1960-е", short:"Микросхема.", desc:"", history:"", work:"", bullets:[], tags:["IC","микросхема"], sources:[], video:"", quiz:[{question:"Что такое интегральная схема?", options:["Транзистор","Микросхема","Процессор"], correct:1}, {question:"Когда появились?", options:["1950-е","1960-е","1970-е"], correct:1}, {question:"Кто открыл?", options:["Нойс","Шокли","Бэббидж"], correct:0}, {question:"Что содержит?", options:["Несколько транзисторов","Один транзистор","Лампы"], correct:0}], image:"https://via.placeholder.com/400x300?text=Integrated+Circuit", modalImage:"https://via.placeholder.com/500x400?text=Integrated+Circuit+Detail" },

  { id:"microprocessor", hall:"hall3", icon:"🖥️", kicker:"Поколения ЭВМ", name:"Микропроцессорные компьютеры", period:"1970-е", short:"Центральный процессор на чипе.", desc:"", history:"", work:"", bullets:[], tags:["микропроцессор"], sources:[], video:"", quiz:[{question:"Что такое микропроцессор?", options:["Процессор на чипе","Большой компьютер","Лампа"], correct:0}, {question:"Когда появился первый?", options:["1971","1960","1980"], correct:0}, {question:"Кто выпустил?", options:["Intel","IBM","Apple"], correct:0}, {question:"Что позволил создать?", options:["Персональные компьютеры","Суперкомпьютеры","Смартфоны"], correct:0}], image:"https://via.placeholder.com/400x300?text=Microprocessor", modalImage:"https://via.placeholder.com/500x400?text=Microprocessor+Detail" },

  { id:"opticalComputer", hall:"hall3", icon:"💡", kicker:"Поколения ЭВМ", name:"Оптические компьютеры", period:"1980-е – настоящее", short:"Вычисления с помощью света.", desc:"", history:"", work:"", bullets:[], tags:["оптика","фотоны"], sources:[], video:"", quiz:[{question:"Что используют оптические компьютеры?", options:["Электроны","Фотоны","Транзисторы"], correct:1}, {question:"Когда начались исследования?", options:["1980-е","1970-е","1990-е"], correct:0}, {question:"Массовые ли они?", options:["Да","Нет","Почти"], correct:1}, {question:"Для чего перспективны?", options:["Для скорости","Для размера","Для цены"], correct:0}], image:"https://via.placeholder.com/400x300?text=Optical+Computer", modalImage:"https://via.placeholder.com/500x400?text=Optical+Computer+Detail" },

  { id:"quantumComputer", hall:"hall3", icon:"⚛️", kicker:"Поколения ЭВМ", name:"Квантовые компьютеры", period:"1990-е – настоящее", short:"Кубиты и суперпозиция.", desc:"", history:"", work:"", bullets:[], tags:["квант","кубиты"], sources:[], video:"", quiz:[{question:"Что такое кубиты?", options:["Биты","Квантовые биты","Транзисторы"], correct:1}, {question:"Когда появились прототипы?", options:["1990-е","1980-е","2000-е"], correct:0}, {question:"Что позволяет суперпозиция?", options:["Параллельные вычисления","Быстрое сложение","Хранение данных"], correct:0}, {question:"Кто предложил теорию?", options:["Фейнман","Непер","Бэббидж"], correct:0}], image:"https://via.placeholder.com/400x300?text=Quantum+Computer", modalImage:"https://via.placeholder.com/500x400?text=Quantum+Computer+Detail" },

  // hall 4 – Классификация современных вычислительных систем
  { id:"super", hall:"hall4", icon:"🏎️", kicker:"Классификация", name:"Суперкомпьютеры", period:"современность", short:"Кластеры и ускорители.", desc:"", history:"", work:"", bullets:[], tags:["HPC"], sources:[], video:"", quiz:[{question:"Для чего используются суперкомпьютеры?", options:["Для науки","Для игр","Для текста"], correct:0}, {question:"Что достигают современные?", options:["Экзафлопсы","Гигафлопсы","Терафлопсы"], correct:0}, {question:"Что используют?", options:["Ускорители","Лампы","Перфокарты"], correct:0}, {question:"Как охлаждаются?", options:["Жидким азотом","Вентиляторами","Льдом"], correct:0}], image:"https://via.placeholder.com/400x300?text=Supercomputer", modalImage:"https://via.placeholder.com/500x400?text=Supercomputer+Detail" },

  { id:"server", hall:"hall4", icon:"🖥️", kicker:"Классификация", name:"Серверы", period:"современность", short:"Вычислительные центры.", desc:"", history:"", work:"", bullets:[], tags:["сервер","облако"], sources:[], video:"", quiz:[{question:"Где работают серверы?", options:["В дата-центрах","Дома","В кармане"], correct:0}, {question:"Что имеют?", options:["RAID-хранилища","Экраны","Клавиатуры"], correct:0}, {question:"Эволюционировали от?", options:["Мэйнфреймов","ПК","Смартфонов"], correct:0}, {question:"Для чего используются?", options:["Обработка данных","Игры","Текст"], correct:0}], image:"https://via.placeholder.com/400x300?text=Server", modalImage:"https://via.placeholder.com/500x400?text=Server+Detail" },

  { id:"pc", hall:"hall4", icon:"💻", kicker:"Классификация", name:"Персональные компьютеры (ПК)", period:"современность", short:"Десктопы и рабочие станции.", desc:"", history:"", work:"", bullets:[], tags:["ПК","десктоп"], sources:[], video:"", quiz:[{question:"Для кого ПК?", options:["Индивидуального использования","Серверов","Суперкомпьютеров"], correct:0}, {question:"Когда стали массовыми?", options:["1975","1980","1990"], correct:0}, {question:"Что включают?", options:["Процессор и память","Только экран","Только клавиатуру"], correct:0}, {question:"Какие ОС?", options:["Windows/Linux/macOS","Android","iOS"], correct:0}], image:"https://via.placeholder.com/400x300?text=PC", modalImage:"https://via.placeholder.com/500x400?text=PC+Detail" },

  { id:"laptop", hall:"hall4", icon:"💻", kicker:"Классификация", name:"Ноутбуки", period:"современность", short:"Мобильные ПК.", desc:"", history:"", work:"", bullets:[], tags:["ноутбук","мобильный"], sources:[], video:"", quiz:[{question:"Что такое ноутбук?", options:["Мобильный ПК","Сервер","Суперкомпьютер"], correct:0}, {question:"Первый когда?", options:["1981","1975","1990"], correct:0}, {question:"Что имеет?", options:["Батарею","RAID","Жидкий азот"], correct:0}, {question:"Компактнее чем?", options:["ПК","Смартфоны","Серверы"], correct:0}], image:"https://via.placeholder.com/400x300?text=Laptop", modalImage:"https://via.placeholder.com/500x400?text=Laptop+Detail" },

  { id:"smartphone", hall:"hall4", icon:"📱", kicker:"Классификация", name:"Смартфоны", period:"современность", short:"Компьютер в кармане.", desc:"", history:"", work:"", bullets:[], tags:["мобильность"], sources:[], video:"", quiz:[{question:"Что такое смартфон?", options:["Компьютер в кармане","ПК","Сервер"], correct:0}, {question:"Когда началась революция?", options:["2007","1981","1975"], correct:0}, {question:"Что содержит?", options:["SoC","RAID","Жидкий азот"], correct:0}, {question:"Главный канал для?", options:["Интернета","Текста","Игр"], correct:0}], image:"https://via.placeholder.com/400x300?text=Smartphone", modalImage:"https://via.placeholder.com/500x400?text=Smartphone+Detail" },

  { id:"iot", hall:"hall4", icon:"🌐", kicker:"Классификация", name:"IoT-устройства", period:"современность", short:"Умные вещи.", desc:"", history:"", work:"", bullets:[], tags:["IoT","сенсоры"], sources:[], video:"", quiz:[{question:"Что такое IoT?", options:["Умные вещи","ПК","Серверы"], correct:0}, {question:"Когда появилась концепция?", options:["1999","2007","1981"], correct:0}, {question:"Что используют?", options:["Микроконтроллеры","SoC","RAID"], correct:0}, {question:"Для чего?", options:["Сенсоры и актуаторы","Игры","Текст"], correct:0}], image:"https://via.placeholder.com/400x300?text=IoT", modalImage:"https://via.placeholder.com/500x400?text=IoT+Detail" },

  { id:"embedded", hall:"hall4", icon:"🔧", kicker:"Классификация", name:"Встроенные системы", period:"современность", short:"Компьютеры в устройствах.", desc:"", history:"", work:"", bullets:[], tags:["встроенные","микроконтроллер"], sources:[], video:"", quiz:[{question:"Где используются встроенные системы?", options:["В устройствах","В дата-центрах","В кармане"], correct:0}, {question:"Существуют с?", options:["1960-х","1990-х","2000-х"], correct:0}, {question:"Что имеют?", options:["Специализированные чипы","Экраны","Клавиатуры"], correct:0}, {question:"Часто без?", options:["ОС","Процессора","Памяти"], correct:0}], image:"https://via.placeholder.com/400x300?text=Embedded", modalImage:"https://via.placeholder.com/500x400?text=Embedded+Detail" },

  // hall 5 – Эволюция средств отображения информации
  { id:"crt", hall:"hall5", icon:"📺", kicker:"Эволюция отображения", name:"ЭЛТ-мониторы", period:"1920-е – 2000-е", short:"Электронно-лучевая трубка.", desc:"", history:"", work:"", bullets:[], tags:["ЭЛТ","аналог"], sources:[], video:"", quiz:[{question:"Что такое ЭЛТ?", options:["Электронно-лучевая трубка","ЖК","OLED"], correct:0}, {question:"Когда использовалась?", options:["1920-е – 2000-е","2000-е – настоящее","1990-е"], correct:0}, {question:"Что рисует?", options:["Луч электронов","Жидкие кристаллы","Органические светодиоды"], correct:0}, {question:"Вытеснена?", options:["Плоскими дисплеями","Лампами","Транзисторами"], correct:0}], image:"https://via.placeholder.com/400x300?text=CRT", modalImage:"https://via.placeholder.com/500x400?text=CRT+Detail" },

  { id:"plasma", hall:"hall5", icon:"✨", kicker:"Эволюция отображения", name:"Плазменные панели", period:"1997 – 2010-е", short:"Газоразрядная технология.", desc:"", history:"", work:"", bullets:[], tags:["плазма","газ"], sources:[], video:"", quiz:[{question:"Что используют плазменные панели?", options:["Инертный газ","Жидкие кристаллы","Органические светодиоды"], correct:0}, {question:"Когда появились?", options:["1997","2000","2010"], correct:0}, {question:"Отличная?", options:["Контрастность","Цена","Размер"], correct:0}, {question:"Вытеснены?", options:["LCD и OLED","ЭЛТ","QLED"], correct:0}], image:"https://via.placeholder.com/400x300?text=Plasma", modalImage:"https://via.placeholder.com/500x400?text=Plasma+Detail" },

  { id:"lcd", hall:"hall5", icon:"💫", kicker:"Эволюция отображения", name:"ЖК-дисплеи", period:"1990-е – настоящее", short:"Жидкие кристаллы с подсветкой.", desc:"", history:"", work:"", bullets:[], tags:["LCD","кристаллы"], sources:[], video:"", quiz:[{question:"Что модулирует ЖК?", options:["Свет","Электроны","Газ"], correct:0}, {question:"Когда массовое производство?", options:["1990-е","1970-е","2000-е"], correct:0}, {question:"Самый распространенный?", options:["Да","Нет","Только для ПК"], correct:0}, {question:"Худшая?", options:["Контрастность","Цена","Размер"], correct:0}], image:"https://via.placeholder.com/400x300?text=LCD", modalImage:"https://via.placeholder.com/500x400?text=LCD+Detail" },

  { id:"oled", hall:"hall5", icon:"🌟", kicker:"Эволюция отображения", name:"OLED-дисплеи", period:"2000-е – настоящее", short:"Органические светодиоды.", desc:"", history:"", work:"", bullets:[], tags:["OLED","самосвет"], sources:[], video:"", quiz:[{question:"Что светит сам?", options:["Каждый пиксель","Подсветка","Кристаллы"], correct:0}, {question:"Когда появились?", options:["2000-е","1990-е","2010-е"], correct:0}, {question:"Идеальный?", options:["Черный","Белый","Серый"], correct:0}, {question:"Проблемы с?", options:["Выгоранием","Контрастом","Размером"], correct:0}], image:"https://via.placeholder.com/400x300?text=OLED", modalImage:"https://via.placeholder.com/500x400?text=OLED+Detail" },
  
  { id:"qled", hall:"hall5", icon:"🎨", kicker:"Эволюция отображения", name:"QLED-дисплеи", period:"2017 – настоящее", short:"Квантовые точки и мини-LED.", desc:"", history:"", work:"", bullets:[], tags:["QLED","мини-LED"], sources:[], video:"", quiz:[{question:"Что используют QLED?", options:["Квантовые точки","Органические светодиоды","Газ"], correct:0}, {question:"Когда появился?", options:["2017","2000","1990"], correct:0}, {question:"Высокая?", options:["Яркость","Цена","Размер"], correct:0}, {question:"Конкурент?", options:["OLED","ЭЛТ","Плазма"], correct:0}], image:"https://via.placeholder.com/400x300?text=QLED", modalImage:"https://via.placeholder.com/500x400?text=QLED+Detail" }
];