const EXHIBITS = [
  // hall 1 – Домеханическая эпоха
  {id:"abacus",
  hall:"hall1",
  icon:"🧮",
  kicker:"Домеханическая эпоха",
  name:"Абак",
  period:"~3000 до н.э.",
  short:"Ручное счетное устройство",
  desc:"Семейство счётных досок, применявшихся для арифметических вычислений со времён древности во множестве цивилизаций и государств вплоть до XVIII века.",
  history:"Впервые абак появился, вероятно, в Древнем Вавилоне в III тысячелетии до н. э. Первоначально представлял собой доску, разграфлённую на полосы или со сделанными углублениями. Устройства, схожие с древнеегипетским абаком находили в различных регионах - в Древней Индии, Западной Европе, Мезоамерике (у Ацтеков), в Центральных Андов (у Инков), на Дальнем Востоке (в Китае и Японии), а так же в России, но уже в более позднее время (XV - XVI века). Стоит отметить, что в России абак (счеты) использовались до второй половины XX века, до появления первых электронных калькуляторов в торговле. В настоящее время абак используется для обучения системе мысленных вычислений, где абак используется не физически, а мысленно, что способствует развитию способностей к счету с быстрой скоростью.",
  work:"Абак позволяет переводить счет в простые перемещения костяшек по разрядам. Каждая костяшка представляет определённое значение, а их расположение соответствует разряду (единицы, десятки, сотни и т.д.). Для выполнения арифметических операций пользователь перемещает костяшки, что позволяет быстро и эффективно производить вычисления без необходимости в письменных записях или устном счете. В зависимости от происхождения абака и его конструкции, правила перемещения костяшек могут различаться, но общая идея заключается в том, что абак служит инструментом для визуализации счета в процессе вычислений.",
  bullets:["Первый аналоговый калькулятор", "Многовековое использование"],
  tags:["счет", "античность"],
  sources:["https://ru.wikipedia.org/wiki/Абак?"],
  video:"https://www.youtube.com/watch?v=jmom9og7ayM",
  videoText:"Счет на абаке - Youtube",
  quiz:[
    {question:"Что такое абак?", options:["Калькулятор","Счетное устройство","Компьютер"], correct:1},
    {question:"В каком веке появился?", options:["I век","III тысячелетие до н.э.","XX век"], correct:1},
    {question:"Как работает?", options:["С электричеством","С костяшками","С шестернями"], correct:1},
    {question:"Где использовался?", options:["В Древнем Египте","В Древней Руси","В Южной Африке"], correct:0}
  ],
  image:"images/hall1/abakus3.png",
  modalImages: [
    "images/hall1/abakus3.png",
    "images/hall1/abakus1.JPG",
    "images/hall1/abakus2.JPG"
    ]},

  {id:"antikythera",
  hall:"hall1",
  icon:"🪐",
  kicker:"Домеханическая эпоха",
  name:"Антикитерский механизм",
  period:"~II–I век до н.э.",
  short:"Механический аналоговый вычислитель.",
  desc:"Древнегреческий астрономический инструмент, предназначенный для моделирования движения небесных тел и предсказания астрономических событий.",
  history:"Артефакт был поднят со дна Эгейского моря греческим водолазом Ликопантисом в 1901 году. Артефакт был найден на затонувшем судне (на глубине от 43 до 62 м) неподалеку от острова Антикитера, который и подарил ему свое имя. Возможно, корабль шёл с острова Родос, где во II веке до нашей эры жил и работал известный греческий астроном и математик Гиппарх Никейский.",
  work:"Механизм представляет собой календарь, а также астрономическое, метеорологическое, образовательное и картографическое устройство, состоящее из 30 бронзовых шестеренок. Это самый древний образец аналогового вычислительного устройства, первая известная механическая Солнечная система, планетарий и астрономические часы. Вращение шестеренок позволяло визуализировать  движение известных в то время планет, предсказывать затмения и другие астрономические явления.",
  bullets:["Первый аналоговый компьютер", "Сложнейший механизм своего времени"],
  tags:["шестерни","астрономия", "античность"],
  sources:[
    "https://habr.com/ru/companies/ua-hosting/articles/547282/", 
    "https://ru.wikipedia.org/wiki/Антикитерский_механизм"
  ],
  video:"https://rutube.ru/video/d2a71b3ebc91a4029b488e47fd4a3c7d/",
  videoText:"Устройство Антикитерского механизма - Рутуб",
  quiz:[
    {question:"Что такое Антикитерский механизм?", options:["Калькулятор","Астрономический инструмент","Телескоп"], correct:1},
    {question:"Когда был найден?", options:["1901 год","1931 год","2000 год"], correct:0},
    {question:"Как работает?", options:["С шестернями","С электричеством","С магнитами"], correct:0},
    {question:"Для чего использовался?", options:["Для счета","Для предсказания затмений","Для письма"], correct:1}
  ],
  modalImages: [
    "images/hall1/antikera2.png",
    "images/hall1/antikera1.jpg",
    "images/hall1/antikera3.jpg",
    "images/hall1/antikera4.png",
    "images/hall1/antikera5.jpeg"
  ]},

  {id:"neperBones",
  hall:"hall1",
  icon:"🏷",
  kicker:"Домеханическая эпоха",
  name:"Палочки Непера",
  period:"1617",
  short:"Инструмент для умножения.",
  desc:"Устройство для умножения и деления, представляющее собой набор прямоугольных палочек, на которых нанесены числа и их произведения.",
  history:"Палочки Непера были созданы шотландским математиком Джоном Непером в 1617 году. Непер был известен своими работами в области логарифмов и тригонометрии.",
  work:"Состоит из 10 палочек, имеющих форму удлинённого прямоугольного параллелепипеда. Каждая из боковых граней палочки делилась поперечными чертами на 9 квадратов, разделённых, в свою очередь, проводимыми в одном и том же направлении диагоналями на пары треугольников. На каждом квадрате была нанесена цифра от 1 до 9, а на диагоналях были указаны произведения этих цифр на номер палочки. Для умножения двух чисел, например 467 и 3, нужно было расположить палочки с цифрами 4, 6 и 7 рядом друг с другом, а затем найти на палочке с цифрой 3 соответствующие произведения. Результат считывался по диагоналям, складывая числа в каждой диагонали для получения окончательного ответа. С гораздо меньшими удобствами производится при помощи этого прибора действие деления.",
  bullets:["Умножение и деление через палочки", "Принцип счета по диагоналям"],
  tags:["умножение","палочки"],
  sources:[
    "https://habr.com/ru/companies/rshb/articles/807291/",
    "https://www.mathematik.uni-marburg.de/~thormae/lectures/ti1/code/napierbones/napierbones.html",
    "https://ru.wikipedia.org/wiki/Палочки_Непера"
  ],
  video:"https://www.youtube.com/watch?v=dkusF7WPTLI",
  videoText:"Умножение с помощью палочек Непера - Youtube",
  quiz:[
    {question:"Кто изобрел?", options:["Паскаль","Непер","Лейбниц"], correct:1},
    {question:"Для чего используются палочки?", options:["Для сложения","Для умножения","Для деления"], correct:1},
    {question:"Когда изобретены?", options:["1617","1642","1673"], correct:0},
    {question:"Как считывается результат?", options:["По диагоналям","По вертикали","По горизонтали"], correct:0}
  ],
  modalImages: [
    "images/hall1/neper.png",
    "images/hall1/neper2.png",
    "images/hall1/neper3.jpg"
  ]},

  {id:"slideRule",
  hall:"hall1",
  icon:"📏",
  kicker:"Домеханическая эпоха",
  name:"Логарифмическая линейка",
  period:"1620–1970-е",
  short:"Аналоговое вычислительное устройство.",
  desc:"Калькулятор для выполнения математических операций, основанный на свойствах логарифмов.",
  history:"Идею, близкую к конструкции логарифмической линейки, высказал в начале XVII века английский астроном Эдмунд Гантер, он предложил нанести на линейку логарифмическую шкалу и с помощью двух циркулей выполнять операции с логарифмами (сложение и вычитание). В 1622 году свой вариант линейки, мало чем отличающийся от современного, опубликовал в трактате «Круги пропорций» Уильям Отред, который и считается автором первой логарифмической линейки. Сначала линейка Отреда была круговой, но в 1633 году было опубликовано описание прямоугольной. Линейка была незаменимым инструментом на протяжении нескольких столетий, до появления электронных калькуляторов в 1970-х годах.",
  work:"Принцип действия логарифмической линейки основан на том, что умножение и деление чисел заменяется соответственно сложением и вычитанием их логарифмов. Простейшая логарифмическая линейка состоит из двух шкал в логарифмическом масштабе, способных передвигаться относительно друг друга. Более сложные линейки содержат дополнительные шкалы на корпусе и движке и прозрачный бегунок — прозрачную рамку, на которой нанесены одна или несколько рисок, позволяющих фиксировать на шкалах числа; бегунок может свободно двигаться вдоль корпуса, визирные линии нанесены перпендикулярно шкалам.\n К примеру, для того чтобы вычислить произведение двух чисел, начало или конец подвижной шкалы совмещают с первым множителем на неподвижной шкале, а на подвижной шкале находят второй множитель. Напротив него на неподвижной шкале находится результат умножения этих чисел: log(x) + log(y) = log(xy).",
  bullets:["Многовековое использование","Умножение и деление через логарифмы"],
  tags:["линейка","логарифм"],
  sources:["https://ru.wikipedia.org/wiki/Логарифмическая_линейка"],
  video:"https://rutube.ru/video/7e03ee5a7048650cd108379a4dc731f3/",
  videoText:"Наглядное умножение на логарифмической линейке - Рутуб",
  quiz:[
    {question:"Что представляла из себя логарифмическая линейка?", options:["Линейка","Калькулятор","Компьютер"], correct:1},
    {question:"На чем основана работа?", options:["Синусах","Косинусах","Логарифмах"], correct:2},
    {question:"Кто придумал ?", options:["Непер","Оутред","Бэббидж"], correct:1},
    {question:"Когда использовалась?", options:["До 1970-х","до 2000-х","в настоящее время"], correct:0}
  ],
  modalImages: [
    "images/hall1/log.png",
    "images/hall1/log1.jpg",
    "images/hall1/log2.jpg"
  ]},

  // hall 2 – Механические и электромеханические вычислители
  {id:"pascaline",
  hall:"hall2",
  icon:"🧷",
  kicker:"Механические вычислители",
  name:"Машина Паскаля",
  period:"1642",
  short:"Механический сумматор.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["механика"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Кто создал машину Паскаля?", options:["Паскаль","Непер","Лейбниц"], correct:0},
    {question:"Для чего создана?", options:["Для счета налогов","Для астрономии","Для ткачества"], correct:0},
    {question:"Как работает?", options:["С зубчатыми колесами","С лампами","С транзисторами"], correct:0},
    {question:"Когда создана?", options:["1642","1673","1804"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Pascaline",
  modalImage:"https://via.placeholder.com/500x400?text=Pascaline+Detail"},

  {id:"leibnizMachine",
  hall:"hall2",
  icon:"⚙️",
  kicker:"Механические вычислители",
  name:"Машина Лейбница",
  period:"1673",
  short:"Улучшенный механический калькулятор.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["Лейбниц","механика"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Кто разработал машину Лейбница?", options:["Паскаль","Лейбниц","Жаккар"], correct:1},
    {question:"Что добавлено к машине Паскаля?", options:["Умножение","Лампы","Транзисторы"], correct:0},
    {question:"Как работает умножение?", options:["С барабанами","С шестернями","С кнопками"], correct:0},
    {question:"Когда разработана?", options:["1642","1673","1804"], correct:1}
  ],
  image:"https://via.placeholder.com/400x300?text=Leibniz+Machine",
  modalImage:"https://via.placeholder.com/500x400?text=Leibniz+Machine+Detail"},

  {id:"jacquardLoom",
  hall:"hall2",
  icon:"🧵",
  kicker:"Электромеханические вычислители",
  name:"Ткацкий станок Жаккара",
  period:"1804",
  short:"Программируемый ткацкий станок.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["ткачество","перфокарты"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Что такое ткацкий станок Жаккара?", options:["Калькулятор","Программируемый станок","Телескоп"], correct:1},
    {question:"Что использовал для управления?", options:["Перфокарты","Кнопки","Экран"], correct:0},
    {question:"Кто изобрел?", options:["Жаккар","Бэббидж","Холлерит"], correct:0},
    {question:"Для чего использовался?", options:["Для ткани","Для счета","Для астрономии"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Jacquard+Loom",
  modalImage:"https://via.placeholder.com/500x400?text=Jacquard+Loom+Detail"},

  {id:"babbage",
  hall:"hall2",
  icon:"🧠",
  kicker:"Проекты универсальных машин",
  name:"Аналитическая машина Бэббиджа",
  period:"1837",
  short:"Проект программируемого компьютера.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["архитектура"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Кто спроектировал Аналитическую машину?", options:["Паскаль","Бэббидж","Холлерит"], correct:1},
    {question:"Была ли построена машина?", options:["Да","Нет","Частично"], correct:1},
    {question:"Из скольких частей состояла?", options:["2","3","4"], correct:1},
    {question:"Что использовалось для управления?", options:["Перфокарты","Кнопки","Экран"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Babbage+Machine",
  modalImage:"https://via.placeholder.com/500x400?text=Babbage+Machine+Detail"},

  {id:"hollerithTabulator",
  hall:"hall2",
  icon:"📊",
  kicker:"Электромеханические вычислители",
  name:"Табулятор Холлерита",
  period:"1890",
  short:"Электромеханическая машина для обработки данных.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["табулятор","IBM"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Для чего использовался табулятор?", options:["Для переписи","Для ткачества","Для астрономии"], correct:0},
    {question:"Кто разработал?", options:["Холлерит","Бэббидж","Жаккар"], correct:0},
    {question:"Что считывалось?", options:["Перфокарты","Кнопки","Экран"], correct:0},
    {question:"Стала основой для?", options:["IBM","Apple","Google"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Hollerith+Tabulator",
  modalImage:"https://via.placeholder.com/500x400?text=Hollerith+Tabulator+Detail"},

  // hall 3 – Поколения ЭВМ
  {id:"vacuum",
  hall:"hall3",
  icon:"🔥",
  kicker:"Поколения ЭВМ",
  name:"Ламповые компьютеры",
  period:"1940-е",
  short:"Электронные лампы.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["лампы"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Что использовалось в ламповых компьютерах?", options:["Транзисторы","Лампы","Микросхемы"], correct:1},
    {question:"Когда появились?", options:["1940-е","1950-е","1960-е"], correct:0},
    {question:"Были ли они большими?", options:["Да","Нет","Средними"], correct:0},
    {question:"Как кодировали данные?", options:["Двоично","Десятично","Шестнадцатерично"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Vacuum+Tubes",
  modalImage:"https://via.placeholder.com/500x400?text=Vacuum+Tubes+Detail"},

  {id:"transistor",
  hall:"hall3",
  icon:"🟢",
  kicker:"Поколения ЭВМ",
  name:"Транзисторные компьютеры",
  period:"1950-е",
  short:"Переход к полупроводникам.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["транзисторы"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Что заменили транзисторы?", options:["Лампы","Микросхемы","Процессоры"], correct:0},
    {question:"Когда появились?", options:["1940-е","1950-е","1960-е"], correct:1},
    {question:"Стали ли они меньше?", options:["Да","Нет","Больше"], correct:0},
    {question:"Как работают транзисторы?", options:["Усиливают сигнал","Генерируют свет","Хранят данные"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Transistor",
  modalImage:"https://via.placeholder.com/500x400?text=Transistor+Detail"},

  {id:"integratedCircuit",
  hall:"hall3",
  icon:"🔁",
  kicker:"Поколения ЭВМ",
  name:"Компьютеры на интегральных схемах",
  period:"1960-е",
  short:"Микросхема.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["IC","микросхема"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Что такое интегральная схема?", options:["Транзистор","Микросхема","Процессор"], correct:1},
    {question:"Когда появились?", options:["1950-е","1960-е","1970-е"], correct:1},
    {question:"Кто открыл?", options:["Нойс","Шокли","Бэббидж"], correct:0},
    {question:"Что содержит?", options:["Несколько транзисторов","Один транзистор","Лампы"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Integrated+Circuit",
  modalImage:"https://via.placeholder.com/500x400?text=Integrated+Circuit+Detail"},

  {id:"microprocessor",
  hall:"hall3",
  icon:"🖥️",
  kicker:"Поколения ЭВМ",
  name:"Микропроцессорные компьютеры",
  period:"1970-е",
  short:"Центральный процессор на чипе.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["микропроцессор"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Что такое микропроцессор?", options:["Процессор на чипе","Большой компьютер","Лампа"], correct:0},
    {question:"Когда появился первый?", options:["1971","1960","1980"], correct:0},
    {question:"Кто выпустил?", options:["Intel","IBM","Apple"], correct:0},
    {question:"Что позволил создать?", options:["Персональные компьютеры","Суперкомпьютеры","Смартфоны"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Microprocessor",
  modalImage:"https://via.placeholder.com/500x400?text=Microprocessor+Detail"},

  {id:"opticalComputer",
  hall:"hall3",
  icon:"💡",
  kicker:"Поколения ЭВМ",
  name:"Оптические компьютеры",
  period:"1980-е – настоящее",
  short:"Вычисления с помощью света.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["оптика","фотоны"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Что используют оптические компьютеры?", options:["Электроны","Фотоны","Транзисторы"], correct:1},
    {question:"Когда начались исследования?", options:["1980-е","1970-е","1990-е"], correct:0},
    {question:"Массовые ли они?", options:["Да","Нет","Почти"], correct:1},
    {question:"Для чего перспективны?", options:["Для скорости","Для размера","Для цены"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Optical+Computer",
  modalImage:"https://via.placeholder.com/500x400?text=Optical+Computer+Detail"},

  {id:"quantumComputer",
  hall:"hall3",
  icon:"⚛️",
  kicker:"Поколения ЭВМ",
  name:"Квантовые компьютеры",
  period:"1990-е – настоящее",
  short:"Кубиты и суперпозиция.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["квант","кубиты"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Что такое кубиты?", options:["Биты","Квантовые биты","Транзисторы"], correct:1},
    {question:"Когда появились прототипы?", options:["1990-е","1980-е","2000-е"], correct:0},
    {question:"Что позволяет суперпозиция?", options:["Параллельные вычисления","Быстрое сложение","Хранение данных"], correct:0},
    {question:"Кто предложил теорию?", options:["Фейнман","Непер","Бэббидж"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Quantum+Computer",
  modalImage:"https://via.placeholder.com/500x400?text=Quantum+Computer+Detail"},

  // hall 4 – Классификация современных вычислительных систем
  {id:"super",
  hall:"hall4",
  icon:"🏎️",
  kicker:"Классификация",
  name:"Суперкомпьютеры",
  period:"современность",
  short:"Кластеры и ускорители.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["HPC"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Для чего используются суперкомпьютеры?", options:["Для науки","Для игр","Для текста"], correct:0},
    {question:"Что достигают современные?", options:["Экзафлопсы","Гигафлопсы","Терафлопсы"], correct:0},
    {question:"Что используют?", options:["Ускорители","Лампы","Перфокарты"], correct:0},
    {question:"Как охлаждаются?", options:["Жидким азотом","Вентиляторами","Льдом"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Supercomputer",
  modalImage:"https://via.placeholder.com/500x400?text=Supercomputer+Detail"},

  {id:"server",
  hall:"hall4",
  icon:"🖥️",
  kicker:"Классификация",
  name:"Серверы",
  period:"современность",
  short:"Вычислительные центры.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["сервер","облако"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Где работают серверы?", options:["В дата-центрах","Дома","В кармане"], correct:0},
    {question:"Что имеют?", options:["RAID-хранилища","Экраны","Клавиатуры"], correct:0},
    {question:"Эволюционировали от?", options:["Мэйнфреймов","ПК","Смартфонов"], correct:0},
    {question:"Для чего используются?", options:["Обработка данных","Игры","Текст"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Server",
  modalImage:"https://via.placeholder.com/500x400?text=Server+Detail"},

  {id:"pc",
  hall:"hall4",
  icon:"💻",
  kicker:"Классификация",
  name:"Персональные компьютеры (ПК)",
  period:"современность",
  short:"Десктопы и рабочие станции.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["ПК","десктоп"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Для кого ПК?", options:["Индивидуального использования","Серверов","Суперкомпьютеров"], correct:0},
    {question:"Когда стали массовыми?", options:["1975","1980","1990"], correct:0},
    {question:"Что включают?", options:["Процессор и память","Только экран","Только клавиатуру"], correct:0},
    {question:"Какие ОС?", options:["Windows/Linux/macOS","Android","iOS"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=PC",
  modalImage:"https://via.placeholder.com/500x400?text=PC+Detail"},

  {id:"laptop",
  hall:"hall4",
  icon:"💻",
  kicker:"Классификация",
  name:"Ноутбуки",
  period:"современность",
  short:"Мобильные ПК.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["ноутбук","мобильный"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Что такое ноутбук?", options:["Мобильный ПК","Сервер","Суперкомпьютер"], correct:0},
    {question:"Первый когда?", options:["1981","1975","1990"], correct:0},
    {question:"Что имеет?", options:["Батарею","RAID","Жидкий азот"], correct:0},
    {question:"Компактнее чем?", options:["ПК","Смартфоны","Серверы"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Laptop",
  modalImage:"https://via.placeholder.com/500x400?text=Laptop+Detail"},

  {id:"smartphone",
  hall:"hall4",
  icon:"📱",
  kicker:"Классификация",
  name:"Смартфоны",
  period:"современность",
  short:"Компьютер в кармане.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["мобильность"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Что такое смартфон?", options:["Компьютер в кармане","ПК","Сервер"], correct:0},
    {question:"Когда началась революция?", options:["2007","1981","1975"], correct:0},
    {question:"Что содержит?", options:["SoC","RAID","Жидкий азот"], correct:0},
    {question:"Главный канал для?", options:["Интернета","Текста","Игр"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Smartphone",
  modalImage:"https://via.placeholder.com/500x400?text=Smartphone+Detail"},

  {id:"iot",
  hall:"hall4",
  icon:"🌐",
  kicker:"Классификация",
  name:"IoT-устройства",
  period:"современность",
  short:"Умные вещи.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["IoT","сенсоры"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Что такое IoT?", options:["Умные вещи","ПК","Серверы"], correct:0},
    {question:"Когда появилась концепция?", options:["1999","2007","1981"], correct:0},
    {question:"Что используют?", options:["Микроконтроллеры","SoC","RAID"], correct:0},
    {question:"Для чего?", options:["Сенсоры и актуаторы","Игры","Текст"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=IoT",
  modalImage:"https://via.placeholder.com/500x400?text=IoT+Detail"},

  {id:"embedded",
  hall:"hall4",
  icon:"🔧",
  kicker:"Классификация",
  name:"Встроенные системы",
  period:"современность",
  short:"Компьютеры в устройствах.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["встроенные","микроконтроллер"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Где используются встроенные системы?", options:["В устройствах","В дата-центрах","В кармане"], correct:0},
    {question:"Существуют с?", options:["1960-х","1990-х","2000-х"], correct:0},
    {question:"Что имеют?", options:["Специализированные чипы","Экраны","Клавиатуры"], correct:0},
    {question:"Часто без?", options:["ОС","Процессора","Памяти"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Embedded",
  modalImage:"https://via.placeholder.com/500x400?text=Embedded+Detail"},

  // hall 5 – Эволюция средств отображения информации
  {id:"crt",
  hall:"hall5",
  icon:"📺",
  kicker:"Эволюция отображения",
  name:"ЭЛТ-мониторы",
  period:"1920-е – 2000-е",
  short:"Электронно-лучевая трубка.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["ЭЛТ","аналог"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Что такое ЭЛТ?", options:["Электронно-лучевая трубка","ЖК","OLED"], correct:0},
    {question:"Когда использовалась?", options:["1920-е – 2000-е","2000-е – настоящее","1990-е"], correct:0},
    {question:"Что рисует?", options:["Луч электронов","Жидкие кристаллы","Органические светодиоды"], correct:0},
    {question:"Вытеснена?", options:["Плоскими дисплеями","Лампами","Транзисторами"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=CRT",
  modalImage:"https://via.placeholder.com/500x400?text=CRT+Detail"},

  {id:"plasma",
  hall:"hall5",
  icon:"✨",
  kicker:"Эволюция отображения",
  name:"Плазменные панели",
  period:"1997 – 2010-е",
  short:"Газоразрядная технология.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["плазма","газ"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Что используют плазменные панели?", options:["Инертный газ","Жидкие кристаллы","Органические светодиоды"], correct:0},
    {question:"Когда появились?", options:["1997","2000","2010"], correct:0},
    {question:"Отличная?", options:["Контрастность","Цена","Размер"], correct:0},
    {question:"Вытеснены?", options:["LCD и OLED","ЭЛТ","QLED"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=Plasma",
  modalImage:"https://via.placeholder.com/500x400?text=Plasma+Detail"},

  {id:"lcd",
  hall:"hall5",
  icon:"💫",
  kicker:"Эволюция отображения",
  name:"ЖК-дисплеи",
  period:"1990-е – настоящее",
  short:"Жидкие кристаллы с подсветкой.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["LCD","кристаллы"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Что модулирует ЖК?", options:["Свет","Электроны","Газ"], correct:0},
    {question:"Когда массовое производство?", options:["1990-е","1970-е","2000-е"], correct:0},
    {question:"Самый распространенный?", options:["Да","Нет","Только для ПК"], correct:0},
    {question:"Худшая?", options:["Контрастность","Цена","Размер"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=LCD",
  modalImage:"https://via.placeholder.com/500x400?text=LCD+Detail"},

  {id:"oled",
  hall:"hall5",
  icon:"🌟",
  kicker:"Эволюция отображения",
  name:"OLED-дисплеи",
  period:"2000-е – настоящее",
  short:"Органические светодиоды.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["OLED","самосвет"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Что светит сам?", options:["Каждый пиксель","Подсветка","Кристаллы"], correct:0},
    {question:"Когда появились?", options:["2000-е","1990-е","2010-е"], correct:0},
    {question:"Идеальный?", options:["Черный","Белый","Серый"], correct:0},
    {question:"Проблемы с?", options:["Выгоранием","Контрастом","Размером"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=OLED",
  modalImage:"https://via.placeholder.com/500x400?text=OLED+Detail"},

  {id:"qled",
  hall:"hall5",
  icon:"🎨",
  kicker:"Эволюция отображения",
  name:"QLED-дисплеи",
  period:"2017 – настоящее",
  short:"Квантовые точки и мини-LED.",
  desc:"",
  history:"",
  work:"",
  bullets:[],
  tags:["QLED","мини-LED"],
  sources:[],
  video:"",
  videoText:"",
  quiz:[
    {question:"Что используют QLED?", options:["Квантовые точки","Органические светодиоды","Газ"], correct:0},
    {question:"Когда появился?", options:["2017","2000","1990"], correct:0},
    {question:"Высокая?", options:["Яркость","Цена","Размер"], correct:0},
    {question:"Конкурент?", options:["OLED","ЭЛТ","Плазма"], correct:0}
  ],
  image:"https://via.placeholder.com/400x300?text=QLED",
  modalImage:"https://via.placeholder.com/500x400?text=QLED+Detail"}
];
